### ISSUE TITLE
Your responsive boton is not working. In the navbar

### ISSUE THREAD

**Issue by MauricioParadaG** [freilind/rx-shop#1]
Your responsive boton is not working. In the navbar

**Comment by freilind** [comment]
hi, i have to work on the responsive part. still in development.
site firebase [https://rx-shop-68554.firebaseapp.com/]

**Comment by MauricioParadaG** [comment]
Yes I saw it in a older  commit https://rx-shop-68554.firebaseapp.com/]

But Somehow it's not there in your last code. Maybe I just did not see the check in the correct file

**Comment by MauricioParadaG** [comment]
Thank you it got solve. I needed to fix it too on my page. You helped me a lot.
