### ISSUE TITLE
Could you help me to fix the query in Orders?

### ISSUE THREAD

**Issue by MauricioParadaG** [freilind/rx-shop#2]

**Comment by MauricioParadaG** [comment]
Oh Hablas español! Mejor aún

Como se implementa el filtro por id? no he podido implementarlo de manera correcta. Su codigo parece interesante. No se implementarlo aún

**Comment by freilind** [comment]
tendría que ver tu código. pero yo lo tengo implementado con snapshotChanges.
`getOrdersByUser(userId: string) {
    return this.db.list('/orders', ref => ref.orderByChild('userId').equalTo(userId)).snapshotChanges()
      .pipe(
        map(changes =>
            changes.map(c => {
                const data = c.payload.val();
                const key = c.payload.key;
                return { key, ...data };
            })
        )
      );
  }`

**Comment by MauricioParadaG** [comment]
Si claro, si es que lo estoy viendo y comprobé que te funciona. Hasta entre en tu página.

No se porque no me funciona, estoy empezando a pensar que es un error mio? no me funciona el filtro. Estoy intentando los últimos cambios, comprobando con tu código. Pero no lo entiendo, todo está igual y sigue sin funcionar. 

Voy a terminar la revisión, pero no se que pueda estar ocurriendo con este filtro. 

Creo que mi problema es, no saber dónde está el problema, no se como saber en cual de todos los componentes me puede estar dando el error que no aplica bien el equalTo(UserId)

**Comment by freilind** [comment]
chequea que la estructura de la bd este así.
<img width="419" alt="imagen" src="https://user-images.githubusercontent.com/5200890/80246810-09925980-863b-11ea-967a-ec0c490794b1.png">

**Comment by MauricioParadaG** [comment]
CLAROOOOOo gracias crack tu eres un Heroe!!!!!!!!!!!!!!

Ahi esta la respuesta, Yo no llame ese campo userId yo lo llame user 
Y como no sabia de consultas ni lo entendia, queria hacerlo y despues entenderlo, he ahi mi  error más claro que el agua

**Comment by MauricioParadaG** [comment]
![database](https://user-images.githubusercontent.com/62025899/80247302-209e6f00-866e-11ea-9365-7675e4e88840.jpg)

**Comment by MauricioParadaG** [comment]
Muchas gracias freilind, me has salvado ya 2 dias de busqueda de cual podia ser mi error y ahora lo veo todo más claro.

Por cierto, me parece mejor usar .valueChanges() 
No hay que escribir todo esto con ayuda de .valueChanges()

.pipe(map(
        changes => changes.map(
          c => {
            const data = c.payload.val() as {};
            const key = c.payload.key;
            return { key, ...data };
          })));

**Comment by freilind** [comment]
De nada. sí es verdad, mejor usar valueChanges si no se necesita tener referencia al nodo.
Pero también estoy aprendiendo firebase y no sabía la diferencia ademas ya lo tenia todo implementado así. Tal vez después  haga un refactor. saludos.
